@startmindmap mindmap
+ AircraftWar
++ 游戏逻辑
+++ 敌机生成
+++ 道具掉落
+++ 子弹发射
+++ 碰撞检测

++ 游戏界面
+++ 难度选择与音量开关
+++ 玩家名输入框
+++ 确认框
+++ 排行榜
+++ 游戏主体画面

++ 资源加载
+++ 图片绘制
+++ 音效播放

++ 数据存储
+++ 游戏数据读取与存储


@endmindmap
